name: culturapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  googleapis: ^13.1.0
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.17
  firebase_storage: ^11.6.7
  hive: ^2.2.3
  path_provider: ^2.1.2
  google_maps_flutter: 2.5.3
  geocoding: ^2.2.0
  image: ^4.1.7
  syncfusion_flutter_datagrid: ^24.2.9
  http: ^0.13.6
  google_nav_bar: ^5.0.6
  url_launcher: ^6.2.6
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sign_in_button: ^3.2.0
  intl: ^0.18.1
  multi_select_flutter: ^4.1.3
  googleapis_auth: ^1.4.1
  geolocator: ^11.0.0
  google_sign_in: ^6.2.1
  carousel_slider: ^4.2.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.8
  image_picker: ^0.8.5+3
  device_info_plus: ^9.0.0
  flutter_rating_bar: ^4.0.1
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  share: ^2.0.4
  barcode_scan2: ^4.3.0
  permission_handler: ^11.3.1
  awesome_notifications: ^0.7.4+1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  assets:
  - assets/lang/es.json
  - assets/lang/ca.json
  - assets/lang/en.json
  - assets/cargador.png
  - assets/pinarte.png
  - assets/pinconfe.png
  - assets/pincarnaval.png
  - assets/pinreciclar.png
  - assets/pincirc.png
  - assets/pincommemoracio.png
  - assets/pinconcert.png
  - assets/pinexpo.png
  - assets/pinfesta.png
  - assets/pininfantil.png
  - assets/pinrecom.png
  - assets/pinruta.png
  - assets/pinteatre.png
  - assets/pinvirtual.png
  - assets/pinbateria.png
  - assets/categoriacirc.png
  - assets/categoriaarte.png
  - assets/categoriareciclar.png
  - assets/categoriaconfe.png
  - assets/categoriacarnaval.png
  - assets/categoriacommemoracio.png
  - assets/categoriaconcert.png
  - assets/categoriaexpo.png
  - assets/categoriafesta.png
  - assets/categoriainfantil.png
  - assets/categoriarecom.png
  - assets/categoriaruta.png
  - assets/categoriavirtual.png
  - assets/categoriabateria.png
  - assets/categoriateatre.png
  - assets/background.png
  - assets/festa.png
  - assets/infantil.png
  - assets/circ.png
  - assets/commem.png
  - assets/expo.png
  - assets/art.png
  - assets/carnav.png
  - assets/concert.png
  - assets/confe.png
  - assets/bateria.png
  - assets/ruta.png
  - assets/reciclar.png
  - assets/virtual.png
  - assets/teatr.png
  - assets/userImage.png
  - assets/loginpicture.png
  - assets/calendar.png
  - assets/logo.png
  - assets/badges/
  
  uses-material-design: true

